Retrieved merge base of RawCommit "ade3c1bd83041c2fb7be4ecb41803aee251ed693" from cache as RawCommit "bbec4520c6be6023aa91eecbf8088523bfe0ba84"
SQL: "SELECT job_name, open_date, closed_date, open_sha1, closed_sha1, universal_build, provider, provider_build_num, span_length FROM downstream_build_failures_from_upstream_inferred_breakages WHERE branch_commit = ?" PARMS: "ade3c1bd83041c2fb7be4ecb41803aee251ed693"
inferred_breakages_retrieval_timing 17.435665
Fetching revision builds
Fetching unmatched commit builds...
Finishing fetchCommitPageInfo.
## :pill: CircleCI build failures summary and remediations
As of commit ade3c1bd83 (more details [on the Dr. CI page](https://dr.pytorch.org/commit-details.html?sha1=ade3c1bd83041c2fb7be4ecb41803aee251ed693)):


---
* **1/3** failures introduced in this PR
* **1/3** tentatively recognized as flaky :snowflake:
    * [Click here to rerun these jobs](https://dr.pytorch.org/rebuild-from-pr-comment.html?sha1=ade3c1bd83041c2fb7be4ecb41803aee251ed693)
* **1/3** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=bbec4520c6be6023aa91eecbf8088523bfe0ba84&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base bbec4520c6 from Mar 21 until Mar 23 (51 commits; 62f11f0a35 - 0e0386b434)
  <details>
  <summary>
  Please rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch https://github.com/pytorch/pytorch viable/strict
  git rebase --onto FETCH_HEAD $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch https://github.com/pytorch/pytorch viable/strict
  git rebase FETCH_HEAD
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


---
### :snowflake: 1 tentatively flaky failure
1 failure **tentatively classified as flaky** but have not triggered reruns to confirm:
#### [![See CircleCI build](https://avatars0.githubusercontent.com/ml/7?s=12)](https://circleci.com/gh/pytorch/pytorch/4912487) [pytorch_windows_vs2019_py36_cuda10.1_build](https://circleci.com/gh/pytorch/pytorch/4912487) (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=110397372) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=110397372)) :snowflake:
<details>
<summary>
<code>  Error generating file</code>
</summary>

```
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/type_traits/function_traits.h(44): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/type_traits/function_traits.h(44): error C2144: syntax error: 'unknown-type' should be preceded by ')'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/type_traits/function_traits.h(44): error C2144: syntax error: 'unknown-type' should be preceded by ';'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/type_traits/function_traits.h(44): error C2238: unexpected token(s) preceding ';'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/type_traits/function_traits.h(44): error C2059: syntax error: ')'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/type_traits/function_traits.h(44): error C2988: unrecognizable template declaration/definition
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/type_traits/function_traits.h(44): error C2059: syntax error: '<end Parse>'
-- Removing C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMaskedChar.cu.obj
C:/Jenkins/Miniconda3/Library/bin/cmake.exe -E remove C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMaskedChar.cu.obj
CMake Error at torch_cuda_generated_THCTensorMaskedChar.cu.obj.Release.cmake:281 (message):
  Error generating file
  C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMaskedChar.cu.obj


 verbose:BOOL=ON -D build_configuration:STRING=Release -D generated_file:STRING=C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/./torch_cuda_generated_THCTensor.cu.obj -D generated_cubin_file:STRING=C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/./torch_cuda_generated_THCTensor.cu.obj.cubin.txt -P C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/torch_cuda_generated_THCTensor.cu.obj.Release.cmake" 
-- Removing C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/./torch_cuda_generated_THCTensor.cu.obj
C:/Jenkins/Miniconda3/Library/bin/cmake.exe -E remove C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/./torch_cuda_generated_THCTensor.cu.obj
-- Generating dependency file: C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/torch_cuda_generated_THCTensor.cu.obj.NVCC-depend
c -IC:/Users/circleci/project/aten/../third_party/catch/single_include -IC:/Users/circleci/project/aten/src/ATen/.. -IC:/Users/circleci/project/build/caffe2/aten/src/ATen -IC:/Users/circleci/project/c10/cuda/../.. -IC:/Users/circleci/project/c10/../ -IC:/Users/circleci/project/caffe2/../torch/csrc/api -IC:/Users/circleci/project/caffe2/../torch/csrc/api/include -IC:/Users/circleci/project/build/third_party/ideep/mkl-dnn/include -IC:/Users/circleci/project/third_party/ideep/mkl-dnn/src/../include
THCTensor.cu 
-- Generating temporary cmake readable file: C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/torch_cuda_generated_THCTensor.cu.obj.depend.tmp
```

</details>


---
Build pytorch_xla_linux_xenial_py3_6_clang7_build is failing. Please create an issue [PT_BREAK] in pytorch/xla and link to to this PR. If you have questions, please reach out to @ailzhang/@dlibenzi/@jackCaoG

---
### :construction: 1 upstream failure:
These were probably **caused by upstream breakages**:
* [pytorch_linux_xenial_py3_clang5_asan_test](https://dr.pytorch.org/build-details.html?build_id=110435982) from Mar 21 until Mar 23 (51 commits; 62f11f0a35 - 0e0386b434)


---
<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

